server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
         locator:
           enabled: true

  #redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000ms

  #数据源
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/gateway?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  thymeleaf:
    catch: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5

#mybatis xml和实体类路径配置
mybatis:
  mapper-locations: classpath:mapping/**/*.xml
  type-aliases-package: com.gettop.gateway.*.model

#开启端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

#日志配置
logging:
  config: classpath:log4j2.yml